### ISSUE TITLE
Support Nordea payments

### ISSUE THREAD

**Issue by Jyrno42** [thorgate/django-thorbanks#4]
Can pretty much follow the same splitting logic as auth system uses, just need to write the implementation.

Note: When fixing this, one should also implement functional tests for SOLO protocol based banklinks (auth/payment.)

**Comment by wanaryytel** [comment]
@Jyrno42 close?

**Comment by Jyrno42** [comment]
Yup.

Note: I also created a new issue for removing SOLO protocol from thorbanks (since there is no need anymore) #12
